version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DATABASE: turing-signing-server-0
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  db_seeder:
    image: andywer/plow:1.1.1
    command: >
      sh -c "
        echo \"Initializing database turing-signing-server-0…\" &&
        node /db/create-dbs.js &&
        PGDATABASE=turing-signing-server-0 /app/plow.js migrate /db/migrations &&
        PGDATABASE=turing-signing-server-0 /app/plow.js seed /db/seeds
      "
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGUSER: postgres
    restart: 'no'
    volumes:
      - ./database:/db:ro
